### ISSUE TITLE
ModuleNotFoundError: No module named 'selenium'

### ISSUE THREAD

**Issue by reeswar21** [SHUR1K-N/MeetNinja-Google-Meet-Bot#26]
Traceback (most recent call last):
  File "/Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 3, in <module>
    from selenium import webdriver; import requests
ModuleNotFoundError: No module named 'selenium'

**Comment by SHUR1K-N** [comment]
It seems you have not installed the required packages to be running MeetNinja. Kindly, refer to [step #2](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot#usage) under the "Usage" subheading within the MeetNinja page:

> PIP-install all the packages mentioned under the last subheading on this page, either automatically via running the pip install -r requirments.txt command, or manually via separate pip install commands for each package

**Comment by reeswar21** [comment]
i have actually done that but its still not working

**Comment by reeswar21** [comment]
<img width="567" alt="Screenshot 2021-05-11 at 9 25 01 PM" src="https://user-images.githubusercontent.com/75256095/117822746-63de7680-b29f-11eb-8e13-3e34d9010765.png">

**Comment by SHUR1K-N** [comment]
Do you still see the same message saying `ModuleNotFoundError: No module named 'selenium'` ?

**Comment by reeswar21** [comment]
yes

**Comment by SHUR1K-N** [comment]
Strange. I found some sensible solutions [here](https://stackoverflow.com/questions/44528638/after-pip-successful-installed-modulenotfounderror) that you could try. Please do, and let me know!

**Comment by reeswar21** [comment]
thanks for the solution and now its stuck on this:

Checking for MeetNinja updates...�[32m You are using the latest version!
�[0m

Initializing browser...�[31m Failed!�[0m

**Comment by SHUR1K-N** [comment]
Uncomment [line #280](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/blob/a84244c56ca209781c0996ff743bb5bd85c2e2c4/MeetNinja.py#L280) from MeetNinja.py:

`# print(e)`

Now, the failure will show itself in the form of a traceback (error message) in the MeetNinja console window. You may then share this traceback here.

**Comment by reeswar21** [comment]
still shows the same thing

**Comment by SHUR1K-N** [comment]
_What_ thing? If you correctly follow my previous comment, it should give you a traceback (error message) instead of the "Failed!" text. It should show you a more descriptive message.

**Comment by reeswar21** [comment]
Checking for MeetNinja updates...[32m You are using the latest version!
[0m

Initializing browser...[31m Failed![0m

it still shows this

**Comment by SHUR1K-N** [comment]
Then you have not followed the previous instruction correctly. Please uncomment line [line #280](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/blob/a84244c56ca209781c0996ff743bb5bd85c2e2c4/MeetNinja.py#L280) from MeetNinja.py:

`# print(e)`

Here, remove the `# `, so it becomes:

`print(e)`


Now, when you save the file and run MeetNinja again, the failure will show itself in a more specific and detailed (a traceback). You may then share this traceback here.

**Comment by reeswar21** [comment]
hi, bro sorry for the late reply..This is the error!

Initializing browser...Traceback (most recent call last):
  File "/Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 246, in <module>
    driver = initBrowser()
  File "/Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 125, in initBrowser
    driver = webdriver.Chrome(service=servicePath, options=chromeOptions)
TypeError: __init__() got an unexpected keyword argument 'service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 278, in <module>
    print(e)
NameError: name 'e' is not defined
>>>

**Comment by SHUR1K-N** [comment]
This problem has already been solved in [this Issue](https://github.com/SHUR1K-N/MeetNinja-Google-Meet-Bot/issues/18). Check the thread out and let me know if the suggested fix solves your problem.

**Comment by reeswar21** [comment]
still the same problem

Initializing browser...Traceback (most recent call last):
  File "/Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 234, in <module>
    driver = initBrowser()
  File "/Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 113, in initBrowser
    driver = webdriver.Chrome(service=servicePath, options=chromeOptions)
TypeError: __init__() got an unexpected keyword argument 'service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 266, in <module>
    print(e)
NameError: name 'e' is not defined
>>>

**Comment by reeswar21** [comment]
and also can explain which part to edit?

**Comment by SHUR1K-N** [comment]
All solutions to the problems you are facing are already given within the "Possible fixes" section of when MeetNinja shows "Failed!". Your problem here may be that you are either not providing permissions correctly (as mentioned within the hyperlinked thread in the previous comment) or your Google Chrome and chromedriver versions are a mismatch. Try updating Google Chrome and then [download the appropriate chromedriver](https://chromedriver.chromium.org/downloads) according to your Google Chrome version

> and also can explain which part to edit?

Could you please be more specific so I could help better?

**Comment by reeswar21** [comment]
Help pls I have no idea where to start now


Initializing browser...Traceback (most recent call last):
  File "/Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 234, in <module>
    driver = initBrowser()
  File "/Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 113, in initBrowser
    driver = webdriver.Chrome(service=servicePath, options=chromeOptions)
TypeError: __init__() got an unexpected keyword argument 'service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/reeswar/MeetNinja-Google-Meet-Bot-master/MeetNinja.py", line 266, in <module>
    print(e)
NameError: name 'e' is not defined
>>>

**Comment by reeswar21** [comment]
The chromedriver is up to date

**Comment by SHUR1K-N** [comment]
Again, you are not providing the correct permissions to MeetNinja. Have you tried executing the `chmod 777 -R ./` command in your terminal from within the MeetNinja directory?

**Comment by reeswar21** [comment]
Yes it says no directory or such file

**Comment by SHUR1K-N** [comment]
Then you are doing it incorrectly. Enter MeetNinja's root directory (where you see MeetNinja.py and other files), and open a terminal window there. Execute the command `pwd` to confirm you are currently in the MeetNinja directory. Once confirmed, executing `chmod 777 -R ./` will most definitely work.

**Comment by reeswar21** [comment]
Where exactly do I open a terminal window?
<img width="719" alt="Screenshot 2021-05-12 at 3 40 01 PM" src="https://user-images.githubusercontent.com/75256095/117937232-55906900-b338-11eb-9e06-afee58352ef2.png">

**Comment by SHUR1K-N** [comment]
Within this very folder itself.

If this is a Mac system, you may have to follow [this guide](https://apple.stackexchange.com/questions/11323/how-can-i-open-a-terminal-window-directly-from-my-current-finder-location) to be able to just right-click in any empty space within a folder to open a terminal window there.

Alternatively, you could just open a terminal window anywhere and just navigate to this folder using the `cd <folder path>` command.

**Comment by reeswar21** [comment]
still the same problem bro
<img width="562" alt="Screenshot 2021-05-12 at 3 58 52 PM" src="https://user-images.githubusercontent.com/75256095/117939770-fed85e80-b33a-11eb-8b0b-d7b0a8aa7847.png">

**Comment by SHUR1K-N** [comment]
Hmm, try `chmod 777 ./ -R`.

**Comment by reeswar21** [comment]
not working

**Comment by SHUR1K-N** [comment]
Could you share the output as before?

**Comment by reeswar21** [comment]
<img width="556" alt="Screenshot 2021-05-12 at 4 06 53 PM" src="https://user-images.githubusercontent.com/75256095/117940880-1cf28e80-b33c-11eb-949f-7cab57a22ce2.png">

**Comment by SHUR1K-N** [comment]
Strange. Could you try passing the absolute path of the MeetNinja directory into the `chmod` command?

`chmod 777 /Users/reeswar/MeetNinja-Google-Meet-Bot-master -R`

**Comment by reeswar21** [comment]
<img width="565" alt="Screenshot 2021-05-12 at 4 13 32 PM" src="https://user-images.githubusercontent.com/75256095/117941790-013bb800-b33d-11eb-9eea-548b9f83c089.png">

**Comment by SHUR1K-N** [comment]
Super strange, I have tried the same with my test machines and it seems to be working 100% fine. This _is_ the correct command to be executed, and it seems to be an issue at your end, for your particular machine. I am afraid I would not be able to help with the `chmod` bit. However, once you have researched the issue and fixed it, and then given the correct permissions to MeetNinja using `chmod`, you may comment here with a further query or create a new Issue. 

For the time being, I am marking this Issue as closed since it is not technically an Issue with MeetNinja.
